services:
  warehouse:
    image: postgres:16
    container_name: bei_warehouse
    environment:
      POSTGRES_DB: bank_dwh
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
